name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Lint Code
      run: npm run lint

    - name: Run Tests
      run: npm test

    - name: Build Project
      run: npm run build

  cd:
    name: Continuous Deployment
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Trigger Vercel Deployment
      run: |
        curl -X POST -d {} "https://api.vercel.com/v1/integrations/deploy/prj_zKSwF1xLZyljvX3zypLLNgd5DeAC/BIh38u842h"

    - name: Notify Team
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{
          "text": "Deployment Successful!",
          "attachments": [
            {
              "title": "Vercel Deployment",
              "title_link": "https://api.vercel.com/v1/integrations/deploy/prj_zKSwF1xLZyljvX3zypLLNgd5DeAC/BIh38u842h",
              "text": "Your project has been successfully deployed to production.",
              "color": "#36a64f"
            }
          ]
        }' "https://hooks.slack.com/services/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"
